// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Context;

namespace ToDoList.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20221121205828_Rename-Task-Variables")]
    partial class RenameTaskVariables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoList.Context.Models.DailyList", b =>
                {
                    b.Property<Guid>("DailyListId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("DailyListId");

                    b.ToTable("DailyList");
                });

            modelBuilder.Entity("ToDoList.Context.Models.OneTask", b =>
                {
                    b.Property<Guid>("OneTaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<string>("Title");

                    b.HasKey("OneTaskId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("ToDoList.Context.Models.TaskDailyList", b =>
                {
                    b.Property<Guid>("OneTaskId");

                    b.Property<Guid>("DailyListId");

                    b.HasKey("OneTaskId", "DailyListId");

                    b.HasIndex("DailyListId");

                    b.ToTable("TaskDailyList");
                });

            modelBuilder.Entity("ToDoList.Context.Models.ToDoList", b =>
                {
                    b.Property<Guid>("ToDoListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("ToDoListId");

                    b.ToTable("ToDoList");

                    b.HasData(
                        new { ToDoListId = new Guid("1f69c0ca-560c-42ae-972d-d2650ee41c63"), Description = "List of chores", Title = "My todo list" }
                    );
                });

            modelBuilder.Entity("ToDoList.Context.Models.ToDoListDailyList", b =>
                {
                    b.Property<Guid>("ToDoListId");

                    b.Property<Guid>("DailyListId");

                    b.HasKey("ToDoListId", "DailyListId");

                    b.HasIndex("DailyListId");

                    b.ToTable("ToDoListDailyList");
                });

            modelBuilder.Entity("ToDoList.Context.Models.TaskDailyList", b =>
                {
                    b.HasOne("ToDoList.Context.Models.DailyList", "DailyList")
                        .WithMany("TaskDailyLists")
                        .HasForeignKey("DailyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoList.Context.Models.OneTask", "OneTask")
                        .WithMany("TaskDailyLists")
                        .HasForeignKey("OneTaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToDoList.Context.Models.ToDoListDailyList", b =>
                {
                    b.HasOne("ToDoList.Context.Models.DailyList", "DailyList")
                        .WithMany("ToDoListDailyLists")
                        .HasForeignKey("DailyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoList.Context.Models.ToDoList", "ToDoList")
                        .WithMany("ToDoListDailyLists")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
